spring:
  datasource:
    url: jdbc:postgresql://61.99.10.111:5432/nova_test
#    url: jdbc:postgresql://localhost:5432/nova_test
    username: postgres
    password: tjdgns123..
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true