spring:
  datasource:
    url: jdbc:mysql://61.99.10.111:3306/NOVA_LIVE?serverTimezone=UTC
    username: su
    password: tjdgns123..
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
